export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export const NODE_LABELS = {
  USER: 'User',
  ITEM: 'Item',
  CATEGORY: 'Category',
  TAG: 'Tag',
} as const;

export const RELATIONSHIP_TYPES = {
  OWNS: 'OWNS',
  BELONGS_TO: 'BELONGS_TO',
  TAGGED_WITH: 'TAGGED_WITH',
  FOLLOWS: 'FOLLOWS',
} as const;